"""
CWNet-focused DSP scoring harness. The agent must not edit this file.

Loads evaldata/ NPZs (generated by generate_eval.py), runs dsp.extract_envelope(),
and scores using CWNet-relevant metrics: timing accuracy, AUC, F1, IoU, rise_ms.

All scoring is done at 500 Hz (ENVELOPE_SR) — the native DSP output rate.

Usage: python evaluate.py
Prints composite score and diagnostics to stdout.
"""
import sys
import time
from pathlib import Path

import numpy as np

from constants import (
    AUDIO_SR, EVAL_DIR, MAX_CHANNELS, MIN_CHANNELS, N_EVAL_SAMPLES,
    SNR_TIERS, WPM_TIERS, W_AUC, W_F1, W_IOU, W_RISE, W_TIMING,
)

SR = 500  # scoring sample rate (ENVELOPE_SR)


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

def load_samples():
    eval_dir = Path(EVAL_DIR)
    if not eval_dir.exists():
        print(f"ERROR: {EVAL_DIR}/ not found — run: uv run python generate_eval.py")
        sys.exit(1)

    npzs = sorted(eval_dir.glob("sample_*.npz"))
    if not npzs:
        print(f"ERROR: no samples in {EVAL_DIR}/ — run: uv run python generate_eval.py")
        sys.exit(1)

    samples = []
    for path in npzs[:N_EVAL_SAMPLES]:
        d = np.load(path, allow_pickle=True)
        samples.append({
            "audio":    d["audio"].astype(np.float32),
            "gt_500":   d["gt_binary"].astype(np.float32),  # (T_500,) at 500 Hz
            "snr_db":   float(d["snr_db"]),
            "wpm":      float(d["wpm"]),
            "tone_freq": float(d["tone_freq"]),
        })
    return samples


# ---------------------------------------------------------------------------
# Metrics — all at 500 Hz
# ---------------------------------------------------------------------------

def _auc(soft, gt):
    """Trapezoidal AUC."""
    gt_bool = gt.astype(bool)
    n_pos = int(np.sum(gt_bool))
    n_neg = int(np.sum(~gt_bool))
    if n_pos == 0 or n_neg == 0:
        return 0.5

    thresholds = np.sort(np.unique(soft))[::-1]
    tprs, fprs = [], []
    for t in thresholds:
        pred = soft >= t
        tprs.append(np.sum(pred & gt_bool) / n_pos)
        fprs.append(np.sum(pred & ~gt_bool) / n_neg)

    tprs = np.array(tprs)
    fprs = np.array(fprs)
    order = np.argsort(fprs)
    return float(np.trapezoid(tprs[order], fprs[order]))


def _norm_rms_timing(soft, gt, wpm, sr=SR):
    """RMS edge timing error / dit_duration. Lower = sharper edges."""
    gt_edges = np.where(np.diff(gt.astype(int)) != 0)[0]
    pred_edges = np.where(np.diff((soft > 0.5).astype(int)) != 0)[0]

    if len(gt_edges) == 0 or len(pred_edges) == 0:
        return 2.0

    errors_ms = [
        abs(int(pred_edges[np.argmin(np.abs(pred_edges - ge))]) - int(ge)) / sr * 1000.0
        for ge in gt_edges
    ]
    rms_ms = float(np.sqrt(np.mean(np.array(errors_ms) ** 2)))
    dit_ms = 1200.0 / wpm
    return rms_ms / dit_ms


def _f1(soft, gt):
    pred = (soft > 0.5).astype(np.float32)
    gt = gt.astype(np.float32)
    tp = float(np.sum(pred * gt))
    fp = float(np.sum(pred * (1.0 - gt)))
    fn = float(np.sum((1.0 - pred) * gt))
    return tp / max(tp + 0.5 * (fp + fn), 1e-9)


def _iou(soft, gt):
    pred = soft > 0.5
    gt_bool = gt.astype(bool)
    return float(np.sum(pred & gt_bool)) / max(float(np.sum(pred | gt_bool)), 1.0)


def _rise_ms(soft, gt, sr=SR):
    """Mean 10→90% rise time at tone onsets (ms). Lower = sharper = better."""
    onsets = np.where(np.diff(gt.astype(int)) > 0)[0]
    times = []
    window = int(0.15 * sr)  # 150 ms
    for e in onsets:
        seg = soft[e: e + window]
        if len(seg) < 5:
            continue
        above_10 = np.where(seg >= 0.1)[0]
        above_90 = np.where(seg >= 0.9)[0]
        if len(above_10) and len(above_90):
            times.append((above_90[0] - above_10[0]) / sr * 1000.0)
    return float(np.mean(times)) if times else 999.0


def _composite(norm_timing, auc, f1, iou, rise_ms_val, wpm):
    dit_ms = 1200.0 / wpm
    timing_score = max(0.0, 1.0 - norm_timing)
    rise_score = max(0.0, 1.0 - rise_ms_val / (0.5 * dit_ms))
    return (
        W_TIMING * timing_score
        + W_AUC * auc
        + W_F1 * f1
        + W_IOU * iou
        + W_RISE * rise_score
    )


def _snr_tier(snr_db):
    for name, (lo, hi) in SNR_TIERS.items():
        if lo <= snr_db < hi:
            return name
    return "high"


def _wpm_tier(wpm):
    for name, (lo, hi) in WPM_TIERS.items():
        if lo <= wpm < hi:
            return name
    return "vfast"


# ---------------------------------------------------------------------------
# Main evaluation
# ---------------------------------------------------------------------------

def run_evaluation():
    t0 = time.time()

    try:
        import dsp
    except Exception as e:
        print(f"IMPORT_ERROR: {e}")
        sys.exit(1)

    samples = load_samples()
    if not samples:
        print("ERROR: no samples loaded")
        sys.exit(1)

    n_channels = None
    results_by_snr = {tier: [] for tier in SNR_TIERS}
    results_by_wpm = {tier: [] for tier in WPM_TIERS}
    all_composites = []
    all_norm_timing = []
    all_auc = []
    all_f1 = []
    all_iou = []
    all_rise = []
    per_channel_auc = None
    issues = []

    for i, s in enumerate(samples):
        try:
            env = dsp.extract_envelope(
                s["audio"], sample_rate=AUDIO_SR, tone_freq=s["tone_freq"]
            )
        except Exception as e:
            print(f"DSP_ERROR on sample {i}: {e}")
            sys.exit(1)

        if env.ndim == 1:
            env = env[:, np.newaxis]

        if n_channels is None:
            n_channels = env.shape[1]
            per_channel_auc = [[] for _ in range(n_channels)]
            if not (MIN_CHANNELS <= n_channels <= MAX_CHANNELS):
                print(f"CHANNEL_ERROR: {n_channels} channels, must be {MIN_CHANNELS}–{MAX_CHANNELS}")
                sys.exit(1)
        elif env.shape[1] != n_channels:
            print(f"CHANNEL_ERROR: inconsistent channels {env.shape[1]} vs {n_channels}")
            sys.exit(1)

        # Align envelope and gt to the same length
        gt = s["gt_500"]
        min_T = min(env.shape[0], len(gt))
        env = env[:min_T]
        gt = gt[:min_T]

        # Channel-mean fusion
        fused = env.mean(axis=1)

        # Per-channel AUC
        for c in range(n_channels):
            try:
                per_channel_auc[c].append(_auc(env[:, c], gt))
            except Exception:
                per_channel_auc[c].append(0.5)

        wpm = s["wpm"]
        norm_timing = _norm_rms_timing(fused, gt, wpm)
        auc = _auc(fused, gt)
        f1 = _f1(fused, gt)
        iou = _iou(fused, gt)
        rise_ms_val = _rise_ms(fused, gt)
        comp = _composite(norm_timing, auc, f1, iou, rise_ms_val, wpm)

        snr_tier = _snr_tier(s["snr_db"])
        if snr_tier in results_by_snr:
            results_by_snr[snr_tier].append(comp)

        wpm_tier = _wpm_tier(wpm)
        if wpm_tier in results_by_wpm:
            results_by_wpm[wpm_tier].append(comp)

        all_composites.append(comp)
        all_norm_timing.append(norm_timing)
        all_auc.append(auc)
        all_f1.append(f1)
        all_iou.append(iou)
        all_rise.append(rise_ms_val)

        if norm_timing > 1.5:
            issues.append(f"sample {i} (snr={s['snr_db']:+.0f}dB wpm={wpm:.0f}): "
                          f"norm_timing={norm_timing:.2f} (very poor)")
        if rise_ms_val > 50.0:
            issues.append(f"sample {i} (snr={s['snr_db']:+.0f}dB wpm={wpm:.0f}): "
                          f"rise_ms={rise_ms_val:.0f} (very slow)")

    elapsed = time.time() - t0

    # === STDOUT OUTPUT (parsed by agent) ===
    print(f"composite: {np.mean(all_composites):.4f}")
    print(f"n_channels: {n_channels}")
    print(f"n_samples: {len(samples)}")
    print(f"eval_time_s: {elapsed:.1f}")
    print()

    print("--- per_snr ---")
    for tier in SNR_TIERS:
        scores = results_by_snr[tier]
        if scores:
            print(f"  {tier}: {np.mean(scores):.4f}  (n={len(scores)})")
        else:
            print(f"  {tier}: n/a")
    print()

    print("--- per_wpm ---")
    for tier in WPM_TIERS:
        scores = results_by_wpm[tier]
        lo, hi = WPM_TIERS[tier]
        label = f"{tier}({lo}-{hi}wpm)"
        if scores:
            print(f"  {label}: {np.mean(scores):.4f}  (n={len(scores)})")
        else:
            print(f"  {label}: n/a")
    print()

    print("--- per_channel_auc ---")
    for c in range(n_channels):
        mean_auc = np.mean(per_channel_auc[c]) if per_channel_auc[c] else 0.0
        print(f"  ch{c}: {mean_auc:.4f}")
    print()

    print("--- per_metric ---")
    print(f"  norm_timing: {np.mean(all_norm_timing):.3f}")
    print(f"  auc: {np.mean(all_auc):.3f}")
    print(f"  f1: {np.mean(all_f1):.3f}")
    print(f"  iou: {np.mean(all_iou):.3f}")
    print(f"  rise_ms: {np.mean(all_rise):.1f}")
    print()

    if issues:
        print("--- issues ---")
        for iss in issues[:10]:
            print(f"  {iss}")
    else:
        print("--- issues: none ---")


if __name__ == "__main__":
    run_evaluation()
